services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html/public
      - ./.dev/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik_proxy

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
      - ./.dev/system/.bashrc:/home/php/.bashrc
      - ./.dev/system/.bash_aliases:/home/php/.bash_aliases
    links:
      - mysql
    networks:
      - traefik_proxy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - .dev/mysql:/docker-entrypoint-initdb.d
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    internal: false
    driver: bridge

volumes:
  database:
